# Generated by Django 2.2 on 2020-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200324_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(default='This is the description area...', max_length=10000),
        ),
    ]
