# Generated by Django 2.2 on 2020-03-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='cp',
        ),
    ]
